#' Function creates Shiny app project directory structured as an R package.
#' @param path The path where to create the project is supplied by the RStudio
#' interface.
#' @param ... Passes other parameters from the RStudio new project wizard
#' @importFrom usethis create_package
#' @importFrom devtools document
#' @export
new_dph_shiny_app <- function(path, ...) {
# FROM POSIT DOCS: https://docs.posit.co/ide/user/ide/guide/productivity/project-templates.html#defining-the-template-metadata
    # # ensure path exists
    # dir.create(path, recursive = TRUE, showWarnings = FALSE)
    #
    # # generate header for file
    # header <- c(
    #     "# This file was generated by a call to 'dphshiny::new_dph_shiny_app()'.",
    #     "# The following inputs were received:",
    #     ""
    # )
    #
    # # collect inputs and paste together as 'Parameter: Value'
    # dots <- list(...)
    # text <- lapply(seq_along(dots), function(i) {
    #     key <- names(dots)[[i]]
    #     val <- dots[[i]]
    #     paste0(key, ": ", val)
    # })
    #
    # ## collect into single text string ----
    # contents <- paste(
    #     paste(header, collapse = "\n"),
    #     paste(text, collapse = "\n"),
    #     sep = "\n"
    # )
    #
    # ## write to index file ----
    # writeLines(contents, con = file.path(path, "INDEX"))

# END POSIT DOCS -------------------------------------------------

    # CHOOSE TEMPLATE FOLDER BASED ON USER INPUT ----

    dots <- list(...)
    template <- switch(dots$template,
        'Vanilla Shiny' = 'vanilla_shiny',
        'bslib Top Navigation + modules' = 'bslib_top_modules',
        'shinydashboard + modules' = 'shiny_dashboard_modules',
        'module_template'
    )

    source_dir <- system.file(
        paste0("app_templates/", template),
        package = "dphshiny"
    )

    destination_dir <- path

    ## Determine and create folders

    folders_to_copy <- list.files(source_dir, full.names = TRUE, recursive = FALSE)
    destination_paths <- sub(source_dir, destination_dir, folders_to_copy)
    dirs_to_create <- unique(destination_paths[file.info(folders_to_copy)$isdir])

    for (dir in dirs_to_create) {
        if (!dir.exists(dir)) {
            dir.create(dir, recursive = TRUE)
        }
    }

    ## Copy files

    files_to_copy <- list.files(source_dir, full.names = TRUE, recursive = TRUE)
    file_destination_paths <- sub(source_dir, destination_dir, files_to_copy)

    for(i in seq_along(files_to_copy)) {
        file.copy(files_to_copy[[i]], file_destination_paths[[i]])
    }

    ## Initiate app as a package ----

    usethis::with_project(path, {

        usethis::use_description(check_name = FALSE)
        devtools::document()
        usethis::use_testthat()
        usethis::use_test('utils.R', open = FALSE)

        writeLines({"
# Tests for functions in utils.R

test_that('demonstration_function() works...', {
    x <- 'My custom message'
    out <- demonstration_function(x)
    expect_true(grepl(x, out))
})
        "}, con = './tests/testthat/test-utils.R')

    }, force = TRUE)


}
